### ISSUE TITLE
Flashcard List

### ISSUE THREAD

**Issue by P-Oliomonte** [eneben/capstone-flip-wise#1]
# Flashcard List

## Value Proposition

**As a user**

**I want to** browse a list of flashcards,

**so that** I can easily access and review the questions I need to study.

## Description

![Image](https://github.com/user-attachments/assets/f232e3d7-d26b-4972-b9d0-23875c5c41bb)

## Acceptance Criteria

- The homepage displays a list of flashcards.
- The flashcard list is headlined with its purpose.
- Each flashcard listing includes:
  - Flashcard question
  - Flashcard answer
  - Flashcard collection it belongs to
- The list supports vertical scrolling to accommodate multiple entries.

## Tasks

- [ ] Create feature branch `feature/flashcard-list`
- [ ] Inspect and adapt the example data in the [assets folder](./assets/flashcards.json)
- [ ] Create component `Flashcard` receiving props question, answer, collection
- [ ] Create component `FlashcardList` which maps over data and returns Flashcard component for every item and receives prop for `Headline`
- [ ] In `pages/index.js` import data from assets and display FlashcardList with Headline `Random Flashcards`
