### ISSUE TITLE
Create new Collection

### ISSUE THREAD

**Issue by eneben** [eneben/capstone-flip-wise#14]
# Create new Collection

## Value Proposition

**As a user**

**I want to** create new collections,

**so that** I can store my flashcards in collections that didn't yet exist.

## Description

![Image](https://github.com/user-attachments/assets/c27b09f3-e42c-4759-a0df-4de1ac98cc6c)

## Acceptance Criteria

- A form for adding a new flashcard in a new collection is accessible by clicking the "+" (Plus) symbol located at the top of the homepage.
- The form is headlined with its purpose.
- The form must contain following labeled fields:
  - Flashcard question (text input)
  - Flashcard answer (text input)
  - Flashcard collection (dropdown menu)
  - Color picker (color section)
- All fields are mandatory.
- The collection is selected from the existing collections list via a dropdown menu.
- The dropdown includes a default option labeled "Please select a collection," which is non-selectable and requires the user to choose a valid collection.
- The dropdown includes an option to add a new collection, labeled "+ Add new collection".
- When the user selects "+ Add New Collection" from the dropdown, a new labeled input field for "Collection Name" and a color-picker field become visible.
- These fields are also mandatory if the user chooses to create a new collection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new collection is added to the top of the collection list.
- The number of cards in a collection is displayed in the burger menu.

## Tasks

- [ ] Create feature branch `feature/create-collections`
- [ ] Modify the existing `FlashcardForm` component that allow users to submit a new collection and assign a color with all fields being mandatory
- [ ] Implement logic to display the labels for the "Collection Name" and "Color Picker" fields only when the user selects the "+ Add New Collection" option in the dropdown. These fields should remain hidden until this option is chosen.
- [ ] New collection name and color value should be added to the collections array. 
- [ ] The collection's id value should match the `collectionId` value in the flashcard. 
- [ ] Use a package to generate id's [ui](https://www.npmjs.com/package/uid)
