### ISSUE TITLE
Delete Collection

### ISSUE THREAD

**Issue by eneben** [eneben/capstone-flip-wise#16]
# Delete Collection

## Value Proposition

**As a user**

**I want to** delete collections that are no longer relevant,

**so that** I can maintain a clean and organised collection list, ensuring it’s always up to date.

## Description

![Image](https://github.com/user-attachments/assets/d05e6633-c472-4989-be1e-e3a8a1c44ee3)

## Acceptance Criteria

- Each collection in the collection list includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the collection and all flashcards are removed from the respective list, and a success message is displayed.
- If all collections are deleted, a message appears indicating that there are no collections and providing an option to add new ones.

## Tasks

- [ ] Create feature branch `feature/delete-collections`
- [ ] Create dynamic dumb button component receiving props: content, onClick, type
- [ ] Include delete button on each Collection in the collections list
- [ ] Declare useState `isDelete` to show and hide confirmation dialog (default value is `false`)
- [ ] Write onClick handler function for delete button: callback function to toggle `isDelete` between `false` and `true`  
- [ ] `isDelete === true` shows confirmation dialog: Confirmation question, cancel button and delete button 
- [ ] Cancel button toggles `isDelete` back to `false` 
- [ ] Delete button triggers function `handleDeleteCollection` that deletes the particular collection from array 
- [ ] Utilize ToastMessage to show success message for 3 seconds
- [ ] Write conditional for an empty array: When empty show message and indicate option to add new flashcard and collection via form

**Comment by SylvieDoumet** [comment]
Good job! Please be more precise in your wording in the following 2 sections 

Acceptance criteria 
option -> button

Task 
Create dynamic dumb button component receiving props: content, onClick, type
-> Create a reusable button component that receives the following props: content, onClick, type 

An add on could be : 
Ensure the button's style and behavior are consistent across different contexts.
