### ISSUE TITLE
Swipe Function

### ISSUE THREAD

**Issue by eneben** [eneben/capstone-flip-wise#26]
# Swipe Function

## Value Proposition

**As a user**

**I want to** swipe cards left or right (in addition to clicking buttons) to mark them as correct or incorrect,

**so that** I can enjoy a faster and smoother experience on mobile devices.

## Description

![Image](https://github.com/user-attachments/assets/bd5bf724-c4b5-4088-9087-61f6598c6f26)

## Acceptance Criteria

- When a user first clicks the `mark as incorrect`-button a toast message appears with a hint: Swipe left to mark as incorrect.
  - When a user first clicks the `mark as correct`-button a toast message appears with a hint: Swipe right to mark as correct.
  - The toast message's color is neutral (p.ex. blue).
- Swiping the flashcard to the left triggers the same logic as clicking the `mark as incorrect`-button.
  - Swiping the flashcard to the right triggers the same logic as clicking the `mark as correct`-button.
  - In addition, as confirmation and to prevent errors, the appropriate icon is displayed on the respective page for 1-2 seconds after swiping (cross on the left, tick on the right - same symbols as in the buttons).
- The swipe animation should be smooth and appealing.
  - The confirmation icons should also be well animated, e.g. bubble effect.
- The swipe function should be available in both Training Mode and Learning Mode.
  - If only one button is available (like in Learning Mode, where you can only mark the cards as correct *or* incorrect), the card can only be swiped in one direction.

## Tasks

- [ ] Create feature branch `feature/swipe-function`
- [ ] Implement the swipe function in both Training Mode and Learning Mode.
- [ ] Reuse existing logic wherever possible.
- [ ] Implement the smooth animation.
- [ ] Create a reusable component `ConfirmationIcon` and make sure the placement of the icons doesn't interfere with other elements.
- [ ] Add logic to disable swiping if only one action is allowed. 
- [ ] Test swipe interactions to ensure there are no conflicts with other touch gestures (p.ex. scrolling, clicking buttons).

**Comment by ahohnsen** [comment]
Hi there!

Just one little thing. 🙂 
I suggest to keep the Value Proposition a bit shorter as it should state the core benefit and no feature-specific details:

_As a user
I want to swipe cards left or right (in addition to clicking buttons) to mark them as correct or incorrect,
so that I can enjoy a faster and smoother experience on mobile devices._

**Comment by eneben** [comment]
> Hi there!
> 
> Just one little thing. 🙂 I suggest to keep the Value Proposition a bit shorter as it should state the core benefit and no feature-specific details:
> 
> _As a user I want to swipe cards left or right (in addition to clicking buttons) to mark them as correct or incorrect, so that I can enjoy a faster and smoother experience on mobile devices._

OK, I'll change that right away. Thanks for your review! :blush:

**Comment by IsabellUrban** [comment]
Hi, we didn't use the swipe function in the learning mode because it would just work in one direction. In addition, we do not have the stack view in learning mode as we do in training mode. We have therefore omitted the swipe function in learning mode.
