### ISSUE TITLE
Mark Flashcard as Correct

### ISSUE THREAD

**Issue by P-Oliomonte** [eneben/capstone-flip-wise#3]
# Mark Flashcard as Correct

## Value Proposition

**As a user**

**I want to** mark flashcards as correctly answered,

**so that** I can focus on studying the ones I have not mastered yet.

## Description

![Image](https://github.com/user-attachments/assets/add01af2-57e5-4a05-b053-237112791035)

## Acceptance Criteria

- Each flashcard in the flashcard list includes a "Mark as Correct" option, visible only on the answer side.
- Clicking the "Mark as Correct" button of a flashcard removes it from the flashcards list and adds it to the archive.
- There is a clearly visible link on the homepage to navigate to the archive page.
- There is a clearly visible link on the archive page to navigate back to the homepage.
- The archive page displays a list of correctly answered flashcards.
- Each correctly answered flashcard in the archive includes a "Mark as Incorrect" option, visible on both the question and answer sides.
- Clicking the "Mark as Incorrect" button of a flashcard removes it from the archive and adds it back to the flashcard list.
- If there are no correctly answered flashcards in the archive, a message is displayed to the user indicating that no flashcards have been correctly answered yet.
- If all flashcards are marked as correct, a message is displayed on the homepage indicating that all flashcards have been correctly answered.

## Tasks

- [ ] Create feature branch `feature/mark-as-correct`
- [ ] create component `MarkCorrectButton` which triggers onClickHandler function to add or toggle a Boolean key of isCorrect to object
- [ ] include mark correct button on each card (backside)
- [ ] create a new page `archive` that renders a list of all flash cards with `isCorrect === true`
- [ ] display only flash cards with value `!isCorrect`
- [ ] create layout component and wrap it around the app component
- [ ] in layout component add a footer with a nav bar containing the options `home` and `archive`
