### ISSUE TITLE
Database in Mongo DB

### ISSUE THREAD

**Issue by IsabellUrban** [eneben/capstone-flip-wise#33]
## Database in Mongo DB

**As a** user
**I want to** be able to store data centralized 
**In order to** be able to access it across devices and browsers

## Acceptance criteria
- Data should be accessible from any device or browser.
- While loading data an indicator of that should be displayed (the word `Loading...` or a loading spinner). 
- If the database connection fails, an error message should be shown.

## Tasks
- [ ] create branch `feature/database`
- [ ] Set up a MongoDB database for centralized storage. 
- [ ] Insert initial data into database. 
- [ ] Insert MONGODB_URI into .env.local and list .env.local in .gitignore
- [ ] Install mongoose. 
- [ ] Implement model with schema in `db/models/Flashcards.js`. 
- [ ] Implement `connect.js` in `db`.
- [ ] Insert folder with file `api/flashcards/index.js` in `pages`. 
- [ ] In `api/flashcards/index.js` write request handler that connects to database via `dbConnect`.
- [ ] Retrieve data  in frontend with useSWR. 
- [ ] Implement loading indicator.
