### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by IsabellUrban** [eneben/capstone-flip-wise#34]
# User Login

## Value Proposition

**As a** user
**I want to** be able to log into the app
**In order to** personalize my data

## Description 

![Image](https://github.com/user-attachments/assets/6c63e19d-38b9-40b5-bd5c-c56967240e8f)

## Acceptance criteria
- When not logged in the user can only select `Learning Mode`, the other buttons are grayed out. 
- When not logged in the user can not create, edit or delete any flashcards or collections from the sample data. 
- A button should be visible in the header which opens the login dialog on click (when logged in a small green tick is visible on the bottom right of the login icon in the header).
- In the menu there is a login option which opens the login dialog on click (and changes to logout option when logged in). 
- The login dialog should offer the options to login with Github or Google account.
- When logged in the user is able to use all functionalities of the app (all modes and creating, editing and deleting collections and flashcards). 
- When the login icon is clicked when the user is logged in, a modal is opening with the logout confirmation dialog. 
- When the logout option in the menu is clicked a modal is opening with the logout confirmation dialog. 
- The logout confirmation dialog offers the option `Logout` and `Cancel`.

## Tasks
- [ ] Create branch `feature/login` 
- [ ] Disable all modes except `Learning Mode` for logged out users. 
- [ ] Disable create, edit or delete functionality for logged out users
- [ ] Install Authentication (next-auth).
- [ ] Create Login UI: Button/icon in header which opens login modal on click. 
- [ ] Add login button to menu which turns to logout when user is logged in (opening login or logout modal)
- [ ] Enable options for logged in user: All modes selectable and create, edit and delete functionality. 
- [ ] Create logout functionality (logout button in menu and button/icon in header)
