### ISSUE TITLE
Create Flashcard

### ISSUE THREAD

**Issue by P-Oliomonte** [eneben/capstone-flip-wise#4]
# Create Flashcard

## Value Proposition

**As a user**

**I want to** create and store new flashcards,

**so that** I can keep track of the information I need to study.

## Description

![Image](https://github.com/user-attachments/assets/025edd39-85ef-4059-a167-7aa7723af790)

## Acceptance Criteria

- A form for adding flashcards is displayed at the top of the homepage.
- The form is headlined with its purpose.
- The form must include labelled fields for:
  - Flashcard question
  - Flashcard answer
  - Flashcard collection
- All fields are mandatory.
- The collection is selected from the existing collections list via a dropdown menu.
- The collection dropdown must include a default option, "Please select a collection", and necessitates a selection.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- Upon form submission, the new flashcard is added to the top of the flashcard list.

## Tasks

- [ ] Create feature branch `feature/create-flashcard`
- [ ] Implement a `FlashcardForm` component that allows users to submit new flashcards with all fields being mandatory
- [ ] Use a package to generate id's [ui](https://www.npmjs.com/package/uid)
