### ISSUE TITLE
Update Collection

### ISSUE THREAD

**Issue by IsabellUrban** [eneben/capstone-flip-wise#44]
## Value proposition

As a user
I want to update the name or the color of my existing collections,
so that I can tailor the collections to better suit my learning needs and preferences.

## Description
![Image](https://github.com/user-attachments/assets/69b4aaa9-b340-44ff-a758-40b467f85154)

## Acceptance criteria
- [ ] Each collection in the collection list includes an easily accessible edit option.
- [ ] When the edit option is clicked, the pre-filled form opens displaying the collection’s existing details for modification.
- [ ] The form now is headlined with "Edit collection".
- [ ] The form allows for edits to  collection details, including:
  - Collection Name
  - Collection Color
- [ ] All fields are mandatory.
- [ ] The form section includes options for both saving and cancelling the action.
- [ ] The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- [ ] Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- [ ] When confirming the save the changes are saved and reflected in the collection. A toast message appears with the text "Collection updated successfully!"
- [ ] When canceling the editing the form disappears.
- [ ] The collection name in the menu is also updated.

## Tasks
- [ ] Create feature branch feature/update-collection
- [ ] Create an Edit Button in the collection `index.js` in Learning-, Training- and Gaming Mode
- [ ] Use the RoundButton component style "edit"
- [ ] Use the RegularButton component for the save and cancel option 
- [ ] Add functionality to pre-fill FlashcardForm component to edit the Collection
- [ ] `pages/api/collections/[id].js` use PATCH method for backend connection
- [ ] Use ToastMessage component Style "success"

**Comment by StephieTack** [comment]
Hey @IsabellUrban, do you intend to show a toast message for the success? Then we would suggest to add a task to your tasklist? :)

**Comment by IsabellUrban** [comment]
> Hey [@IsabellUrban](https://github.com/IsabellUrban), do you intend to show a toast message for the success? Then we would suggest to add a task to your tasklist? :)

I implemented your suggested changes. Thanks! :-)
