### ISSUE TITLE
Delete Flashcard

### ISSUE THREAD

**Issue by P-Oliomonte** [eneben/capstone-flip-wise#5]
# Delete Flashcard

## Value Proposition

**As a user**

**I want to** delete flashcards that are no longer relevant,

**so that** I can maintain a clean and organised flashcard list, ensuring it’s always up to date.

## Description

![Image](https://github.com/user-attachments/assets/61371a7e-d3c6-4cfd-a3d7-6ff85f1f14d3)

![Image](https://github.com/user-attachments/assets/31ec6fb1-09ad-43ef-a304-e380cb64a0d4)

## Acceptance Criteria

- Each flashcard in the flashcard list and the archive includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the flashcard is removed from the respective list, and a success message is displayed.
- If all flashcards are deleted, a message appears indicating that there are no flashcards and providing an option to add new ones.

## Tasks

- [ ] Create feature branch `feature/delete-flashcard`
- [ ] Create dynamic dumb button component receiving props: content, onClick, type
- [ ] Include delete button on each Flashcard
- [ ] Declare useState `isDelete` to show and hide confirmation dialog (default value is `false`)
- [ ] Write onClick handler function for delete button: callback function to toggle `isDelete` between `false` and `true`  
- [ ] `isDelete === true` shows confirmation dialog: Confirmation question, cancel button and delete button 
- [ ] Cancel button toggles `isDelete` back to `false` 
- [ ] Delete button triggers function `handleDeleteCard` that deletes the particular card from array 
- [ ] Utilize useEffect to show success message for 3 seconds
- [ ] Write conditional for an empty array: When empty show message and indicate option to add new flashcard via form
