### ISSUE TITLE
Update Flashcard

### ISSUE THREAD

**Issue by P-Oliomonte** [eneben/capstone-flip-wise#6]
# Update Flashcard

## Value Proposition

**As a user**

**I want to** update the details of existing flashcards,

**so that** I can tailor the questions to better suit my learning needs and preferences.

## Description

![Image](https://github.com/user-attachments/assets/8c7a7b97-8591-48e9-a10e-988d8afa1586)

## Acceptance Criteria

- Each flashcard in the flashcard list and archive includes an easily accessible edit option.
- When clicking the edit option the page jumps to the top where the pre-filled form with the flashcard’s existing details for modification is shown. 
- The form now is headlined with "Edit flashcard"
- The form allows for edits to all flashcard details, including:
  - Flashcard question
  - Flashcard answer
  - Flashcard collection
- All fields are mandatory.
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- When confirming the save the changes are saved and reflected in the card. 
- When canceling the editing the form is cleared and the heading changes back to "Create new flashcard"
- When the user types long words inside form fields when creating or editing a flashcard the word should break and not overlap the edges when displayed on the flashcard

## Tasks

- [ ] Create feature branch `feature/update-flashcard`
- [ ] The flashcard component should receive the headline as prop
- [ ] Create an Edit Button on the CardComponent
- [ ] Render the `Button` component with save and cancel option and add them to form when edited. 
- [ ] Add functionality to pre-fill `FlashcardForm` component and jump to top of page to edit the Flashcard
- [ ] Implement breaking into next line for long words on flashcards

**Comment by JessicaLoers** [comment]
super duper wireframe 🚀
